excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://simonredar.github.io
title: Cheap Dental Crowns
email: simonredar@gmail.com
author: simonredar
description: My awesome new site
paginate: 3
google_analytics: 